"""Markdown minutes rendering."""

from __future__ import annotations

import re
from collections import Counter

from .models import MeetingRecord, MotionRecord


def meeting_slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip().lower()).strip("-")
    return slug or "board-meeting"


def vote_tally(motion: MotionRecord) -> dict[str, int]:
    counts = Counter(vote.option for vote in motion.votes)
    return {option: counts.get(option, 0) for option in motion.options}


def render_minutes(meeting: MeetingRecord) -> str:
    lines = _meeting_header(meeting)
    lines.extend(_attendance_lines(meeting))
    lines.extend(_conversation_lines(meeting))
    lines.extend(_motion_lines(meeting))
    lines.extend(["", "_Draft minutes generated by Kuzuryu Board Meetings._"])
    return "\n".join(lines)


def _meeting_header(meeting: MeetingRecord) -> list[str]:
    lines = [
        f"# Draft Minutes - {meeting.title}",
        "",
        f"- Meeting ID: `{meeting.id}`",
        f"- Workspace: `{meeting.workspace_id}`",
        f"- Channel: `{meeting.channel_id}`",
        f"- Status: `{meeting.status}`",
        f"- Started: `{meeting.started_at.isoformat()}`",
        f"- Closed: `{meeting.closed_at.isoformat() if meeting.closed_at else 'open'}`",
    ]
    chair = meeting.chair_name or meeting.chair_id
    if chair:
        lines.append(f"- Chair: {chair}")
    return lines


def _attendance_lines(meeting: MeetingRecord) -> list[str]:
    lines = ["", "## Attendance / Quorum"]
    present = [attendee for attendee in meeting.attendance if attendee.present]
    lines.extend(f"- {attendee.name}" for attendee in present)
    if not present:
        lines.append("- No attendees recorded.")
    return lines


def _conversation_lines(meeting: MeetingRecord) -> list[str]:
    lines = ["", "## Conversation"]
    if not meeting.messages:
        return [*lines, "- No channel messages captured."]
    for message in sorted(meeting.messages, key=lambda item: item.message_ts):
        speaker = message.user_name or message.user_id or "unknown"
        lines.append(f"- `{message.message_ts}` {speaker}: {message.text}")
    return lines


def _motion_lines(meeting: MeetingRecord) -> list[str]:
    lines = ["", "## Motions"]
    if not meeting.motions:
        return [*lines, "- No motions recorded."]
    for motion in meeting.motions:
        lines.extend(_single_motion_lines(motion))
    return lines


def _single_motion_lines(motion: MotionRecord) -> list[str]:
    lines = [
        f"### {motion.id}",
        f"- Text: {motion.text}",
        f"- Status: `{motion.status}`",
        f"- Created: `{motion.created_at.isoformat()}`",
        f"- Closed: `{motion.closed_at.isoformat() if motion.closed_at else 'open'}`",
        "- Tally:",
    ]
    lines.extend(f"  - {option}: {count}" for option, count in vote_tally(motion).items())
    lines.extend(_vote_lines(motion))
    return lines


def _vote_lines(motion: MotionRecord) -> list[str]:
    if not motion.votes:
        return ["- Votes: none"]
    lines = ["- Votes:"]
    for vote in sorted(motion.votes, key=lambda item: item.cast_at):
        voter = vote.voter_name or vote.voter_id
        lines.append(f"  - {voter}: {vote.option} at `{vote.cast_at.isoformat()}`")
    return lines

